def ResolvePokemon(cell):
    pokemon = (cell, 0)

    forms = {
        "Deoxys-A" : ("Deoxys", 1),
        "Deoxys-D" : ("Deoxys", 2),
        "Deoxys-S" : ("Deoxys", 3),
        "Wormadam-Sandy" : ("Wormadam", 1),
        "Wormadam-Trash" : ("Wormadam", 2),
        "Rotom-Heat" : ("Rotom", 1),
        "Rotom-Wash" : ("Rotom", 2),
        "Rotom-Frost" : ("Rotom", 3),
        "Rotom-Fan" : ("Rotom", 4),
        "Rotom-Mow" : ("Rotom", 5),
        "Giratina-O" : ("Giratina", 1),
        "Shaymin-S" : ("Shaymin", 1),

        "Rattata-A" : ("Rattata", 1),
        "Raticate-A" : ("Raticate", 1),
        "Raichu-A" : ("Raichu", 1),
        "Sandshrew-A" : ("Sandshrew", 1),
        "Sandslash-A" : ("Sandslash", 1),
        "Vulpix-A" : ("Vulpix", 1),
        "Ninetales-A" : ("Ninetales", 1),
        "Diglett-A" : ("Diglett", 1),
        "Dugtrio-A" : ("Dugtrio", 1),
        "Meowth-A" : ("Meowth", 1),
        "Persian-A" : ("Persian", 1),
        "Geodude-A" : ("Geodude", 1),
        "Graveler-A" : ("Graveler", 1),
        "Golem-A" : ("Golem", 1),
        "Grimer-A" : ("Grimer", 1),
        "Muk-A" : ("Muk", 1),
        "Exeggutor-A" : ("Exeggutor", 1),
        "Marowak-A" : ("Marowak", 1),

        "Meowth-G" : ("Meowth", 2),
        "Ponyta-G" : ("Ponyta", 1),
        "Rapidash-G" : ("Rapidash", 1),
        "Slowpoke-G" : ("Slowpoke", 1),
        "Slowbro-G" : ("Slowbro", 1),
        "Farfetch'd-G" : ("Farfetch'd", 1),
        "Weezing-G" : ("Weezing", 1),
        "Mr. Mime-G" : ("Mr. Mime", 1),
        "Articuno-G" : ("Articuno", 1),
        "Zapdos-G" : ("Zapdos", 1),
        "Moltres-G" : ("Moltres", 1),
        "Slowking-G" : ("Slowking", 1),
        "Corsola-G" : ("Corsola", 1),
        "Zigzagoon-G" : ("Zigzagoon", 1),
        "Linoone-G" : ("Linoone", 1),
        "Darumaka-G" : ("Darumaka", 1),
        "Darmanitan-G" : ("Darmanitan", 1),
        "Yamask-G" : ("Yamask", 1),
        "Stunfisk-G" : ("Stunfisk", 1),

        "Growlithe-H" : ("Growlithe", 1),
        "Arcanine-H" : ("Arcanine", 1),
        "Voltorb-H" : ("Voltorb", 1),
        "Electrode-H" : ("Electrode", 1),
        "Typhlosion-H" : ("Typhlosion", 1),
        "Qwilfish-H" : ("Qwilfish", 1),
        "Sneasel-H" : ("Sneasel", 1),
        "Samurott-H" : ("Samurott", 1),
        "Lilligant-H" : ("Lilligant", 1),
        "Zorua-H" : ("Zorua", 1),
        "Zoroark-H" : ("Zoroark", 1),
        "Braviary-H" : ("Braviary", 1),
        "Sliggoo-H" : ("Sliggoo", 1),
        "Goodra-H" : ("Goodra", 1),
        "Avalugg-H" : ("Avalugg", 1),
        "Decidueye-H" : ("Decidueye", 1),

        "Maushold-F" : ("Maushold", 1),
        "Squawkabilly-B" : ("Squawkabilly", 1),
        "Squawkabilly-Y" : ("Squawkabilly", 2),
        "Squawkabilly-W" : ("Squawkabilly", 3),
        "Palafin-H" : ("Palafin", 1),
        "Tatsugiri-Droopy" : ("Tatsugiri", 1),
        "Tatsugiri-Stretchy" : ("Tatsugiri", 2),
        "Dudunsparce-T-S" : ("Dudunsparce", 1),
        "Gimmighoul-R" : ("Gimmighoul", 1),
        "Wooper-P" : ("Wooper", 1),
        "Tauros-P-C" : ("Tauros", 1),
        "Tauros-P-B" : ("Tauros", 2),
        "Tauros-P-A" : ("Tauros", 3),
        "Oinkologne-F" : ("Oinkologne", 1),
        "Ogerpon-W" : ("Ogerpon", 1),
        "Ogerpon-H" : ("Ogerpon", 2),
        "Ogerpon-C" : ("Ogerpon", 3),
        "Ogerpon-T-T" : ("Ogerpon", 4),
        "Ogerpon-W-T" : ("Ogerpon", 5),
        "Ogerpon-H-T" : ("Ogerpon", 6),
        "Ogerpon-C-T" : ("Ogerpon", 7),
        "Ursaluna-BM" : ("Ursaluna", 1),
        "Terapagos-T" : ("Terapagos", 1),
        "Terapagos-S" : ("Terapagos", 2),
    }

    arceusForms = {
    }

    megas = {
    }

    return forms.get(cell, pokemon)

# SPECIES_REVAVROOM_SEGIN (SPECIES_PALDEAN_FORMS_START + 14)
# SPECIES_REVAVROOM_SCHEDAR (SPECIES_PALDEAN_FORMS_START + 15)
# SPECIES_REVAVROOM_NAVI (SPECIES_PALDEAN_FORMS_START + 16)
# SPECIES_REVAVROOM_RUCHBAH (SPECIES_PALDEAN_FORMS_START + 17)
# SPECIES_REVAVROOM_CAPH (SPECIES_PALDEAN_FORMS_START + 18)
# SPECIES_KORAIDON_LIMITED_BUILD (SPECIES_PALDEAN_FORMS_START + 19)
# SPECIES_KORAIDON_SPRINTING_BUILD (SPECIES_PALDEAN_FORMS_START + 20)
# SPECIES_KORAIDON_SWIMMING_BUILD (SPECIES_PALDEAN_FORMS_START + 21)
# SPECIES_KORAIDON_GLIDING_BUILD (SPECIES_PALDEAN_FORMS_START + 22)
# SPECIES_MIRAIDON_LOW_POWER_MODE (SPECIES_PALDEAN_FORMS_START + 23)
# SPECIES_MIRAIDON_DRIVE_MODE (SPECIES_PALDEAN_FORMS_START + 24)
# SPECIES_MIRAIDON_AQUATIC_MODE (SPECIES_PALDEAN_FORMS_START + 25)
# SPECIES_MIRAIDON_GLIDE_MODE (SPECIES_PALDEAN_FORMS_START + 26)
# SPECIES_POLTCHAGEIST_MASTERPIECE (SPECIES_PALDEAN_FORMS_START + 27)
# SPECIES_SINISTCHA_MASTERPIECE (SPECIES_PALDEAN_FORMS_START + 28)

#  SPECIES_PIKACHU_COSPLAY (SPECIES_MISC_FORM_START)
#  SPECIES_PIKACHU_ROCK_STAR (SPECIES_MISC_FORM_START + 1)
#  SPECIES_PIKACHU_BELLE (SPECIES_MISC_FORM_START + 2)
#  SPECIES_PIKACHU_POP_STAR (SPECIES_MISC_FORM_START + 3)
#  SPECIES_PIKACHU_PH_D (SPECIES_MISC_FORM_START + 4)
#  SPECIES_PIKACHU_LIBRE (SPECIES_MISC_FORM_START + 5)

#  SPECIES_PIKACHU_ORIGINAL_CAP (SPECIES_MISC_FORM_START + 6)
#  SPECIES_PIKACHU_HOENN_CAP (SPECIES_MISC_FORM_START + 7)
#  SPECIES_PIKACHU_SINNOH_CAP (SPECIES_MISC_FORM_START + 8)
#  SPECIES_PIKACHU_UNOVA_CAP (SPECIES_MISC_FORM_START + 9)
#  SPECIES_PIKACHU_KALOS_CAP (SPECIES_MISC_FORM_START + 10)
#  SPECIES_PIKACHU_ALOLA_CAP (SPECIES_MISC_FORM_START + 11)
#  SPECIES_PIKACHU_PARTNER_CAP (SPECIES_MISC_FORM_START + 12)
#  SPECIES_PIKACHU_WORLD_CAP (SPECIES_MISC_FORM_START + 13)

#  SPECIES_CASTFORM_SUNNY (SPECIES_MISC_FORM_START + 14)
#  SPECIES_CASTFORM_RAINY (SPECIES_MISC_FORM_START + 15)
#  SPECIES_CASTFORM_SNOWY (SPECIES_MISC_FORM_START + 16)

#  SPECIES_CHERRIM_SUNSHINE (SPECIES_MISC_FORM_START + 17)
#  SPECIES_SHELLOS_EAST_SEA (SPECIES_MISC_FORM_START + 18)
#  SPECIES_GASTRODON_EAST_SEA (SPECIES_MISC_FORM_START + 19)

#  SPECIES_DIALGA_ORIGIN (SPECIES_MISC_FORM_START + 20)
#  SPECIES_PALKIA_ORIGIN (SPECIES_MISC_FORM_START + 21)

#  SPECIES_BASCULIN_BLUE_STRIPED (SPECIES_MISC_FORM_START + 22)
#  SPECIES_BASCULIN_WHITE_STRIPED (SPECIES_MISC_FORM_START + 23)

#  SPECIES_DARMANITAN_ZEN_MODE (SPECIES_MISC_FORM_START + 24)
#  SPECIES_DARMANITAN_ZEN_MODE_GALARIAN (SPECIES_MISC_FORM_START + 25)

#  SPECIES_DEERLING_SUMMER (SPECIES_MISC_FORM_START + 26)
#  SPECIES_DEERLING_AUTUMN (SPECIES_MISC_FORM_START + 27)
#  SPECIES_DEERLING_WINTER (SPECIES_MISC_FORM_START + 28)

#  SPECIES_SAWSBUCK_SUMMER (SPECIES_MISC_FORM_START + 29)
#  SPECIES_SAWSBUCK_AUTUMN (SPECIES_MISC_FORM_START + 30)
#  SPECIES_SAWSBUCK_WINTER (SPECIES_MISC_FORM_START + 31)

#  SPECIES_TORNADUS_THERIAN (SPECIES_MISC_FORM_START + 32)
#  SPECIES_THUNDURUS_THERIAN (SPECIES_MISC_FORM_START + 33)
#  SPECIES_LANDORUS_THERIAN (SPECIES_MISC_FORM_START + 34)

#  SPECIES_KYUREM_WHITE (SPECIES_MISC_FORM_START + 35)
#  SPECIES_KYUREM_BLACK (SPECIES_MISC_FORM_START + 36)

#  SPECIES_KELDEO_RESOLUTE (SPECIES_MISC_FORM_START + 37)
#  SPECIES_MELOETTA_PIROUETTE (SPECIES_MISC_FORM_START + 38)

#  SPECIES_GENESECT_DOUSE_DRIVE (SPECIES_MISC_FORM_START + 39)
#  SPECIES_GENESECT_SHOCK_DRIVE (SPECIES_MISC_FORM_START + 40)
#  SPECIES_GENESECT_BURN_DRIVE (SPECIES_MISC_FORM_START + 41)
#  SPECIES_GENESECT_CHILL_DRIVE (SPECIES_MISC_FORM_START + 42)

#  SPECIES_GRENINJA_BATTLE_BOND (SPECIES_MISC_FORM_START + 43)
#  SPECIES_GRENINJA_ASH (SPECIES_MISC_FORM_START + 44)

#  SPECIES_VIVILLON_POLAR (SPECIES_MISC_FORM_START + 45)
#  SPECIES_VIVILLON_TUNDRA (SPECIES_MISC_FORM_START + 46)
#  SPECIES_VIVILLON_CONTINENTAL (SPECIES_MISC_FORM_START + 47)
#  SPECIES_VIVILLON_GARDEN (SPECIES_MISC_FORM_START + 48)
#  SPECIES_VIVILLON_ELEGANT (SPECIES_MISC_FORM_START + 49)
#  SPECIES_VIVILLON_MEADOW (SPECIES_MISC_FORM_START + 50)
#  SPECIES_VIVILLON_MODERN (SPECIES_MISC_FORM_START + 51)
#  SPECIES_VIVILLON_MARINE (SPECIES_MISC_FORM_START + 52)
#  SPECIES_VIVILLON_ARCHIPELAGO (SPECIES_MISC_FORM_START + 53)
#  SPECIES_VIVILLON_HIGH_PLAINS (SPECIES_MISC_FORM_START + 54)
#  SPECIES_VIVILLON_SANDSTORM (SPECIES_MISC_FORM_START + 55)
#  SPECIES_VIVILLON_RIVER (SPECIES_MISC_FORM_START + 56)
#  SPECIES_VIVILLON_MONSOON (SPECIES_MISC_FORM_START + 57)
#  SPECIES_VIVILLON_SAVANNA (SPECIES_MISC_FORM_START + 58)
#  SPECIES_VIVILLON_SUN (SPECIES_MISC_FORM_START + 59)
#  SPECIES_VIVILLON_OCEAN (SPECIES_MISC_FORM_START + 60)
#  SPECIES_VIVILLON_JUNGLE (SPECIES_MISC_FORM_START + 61)
#  SPECIES_VIVILLON_FANCY (SPECIES_MISC_FORM_START + 62)
#  SPECIES_VIVILLON_POKE_BALL (SPECIES_MISC_FORM_START + 63)

#  SPECIES_FLABEBE_YELLOW_FLOWER (SPECIES_MISC_FORM_START + 64)
#  SPECIES_FLABEBE_ORANGE_FLOWER (SPECIES_MISC_FORM_START + 65)
#  SPECIES_FLABEBE_BLUE_FLOWER (SPECIES_MISC_FORM_START + 66)
#  SPECIES_FLABEBE_WHITE_FLOWER (SPECIES_MISC_FORM_START + 67)

#  SPECIES_FLOETTE_YELLOW_FLOWER (SPECIES_MISC_FORM_START + 68)
#  SPECIES_FLOETTE_ORANGE_FLOWER (SPECIES_MISC_FORM_START + 69)
#  SPECIES_FLOETTE_BLUE_FLOWER (SPECIES_MISC_FORM_START + 70)
#  SPECIES_FLOETTE_WHITE_FLOWER (SPECIES_MISC_FORM_START + 71)
#  SPECIES_FLOETTE_ETERNAL_FLOWER (SPECIES_MISC_FORM_START + 72)

#  SPECIES_FLORGES_YELLOW_FLOWER (SPECIES_MISC_FORM_START + 73)
#  SPECIES_FLORGES_ORANGE_FLOWER (SPECIES_MISC_FORM_START + 74)
#  SPECIES_FLORGES_BLUE_FLOWER (SPECIES_MISC_FORM_START + 75)
#  SPECIES_FLORGES_WHITE_FLOWER (SPECIES_MISC_FORM_START + 76)

#  SPECIES_FURFROU_HEART (SPECIES_MISC_FORM_START + 77)
#  SPECIES_FURFROU_STAR (SPECIES_MISC_FORM_START + 78)
#  SPECIES_FURFROU_DIAMOND (SPECIES_MISC_FORM_START + 79)
#  SPECIES_FURFROU_DEBUTANTE (SPECIES_MISC_FORM_START + 80)
#  SPECIES_FURFROU_MATRON (SPECIES_MISC_FORM_START + 81)
#  SPECIES_FURFROU_DANDY (SPECIES_MISC_FORM_START + 82)
#  SPECIES_FURFROU_LA_REINE (SPECIES_MISC_FORM_START + 83)
#  SPECIES_FURFROU_KABUKI (SPECIES_MISC_FORM_START + 84)
#  SPECIES_FURFROU_PHARAOH (SPECIES_MISC_FORM_START + 85)

#  SPECIES_AEGISLASH_BLADE (SPECIES_MISC_FORM_START + 86)

#  SPECIES_PUMPKABOO_SMALL (SPECIES_MISC_FORM_START + 87)
#  SPECIES_PUMPKABOO_LARGE (SPECIES_MISC_FORM_START + 88)
#  SPECIES_PUMPKABOO_SUPER (SPECIES_MISC_FORM_START + 89)

#  SPECIES_GOURGEIST_SMALL (SPECIES_MISC_FORM_START + 90)
#  SPECIES_GOURGEIST_LARGE (SPECIES_MISC_FORM_START + 91)
#  SPECIES_GOURGEIST_SUPER (SPECIES_MISC_FORM_START + 92)

#  SPECIES_XERNEAS_ACTIVE (SPECIES_MISC_FORM_START + 93)

#  SPECIES_ZYGARDE_10 (SPECIES_MISC_FORM_START + 94)
#  SPECIES_ZYGARDE_10_POWER_CONSTRUCT (SPECIES_MISC_FORM_START + 95)
#  SPECIES_ZYGARDE_50_POWER_CONSTRUCT (SPECIES_MISC_FORM_START + 96)
#  SPECIES_ZYGARDE_10_COMPLETE (SPECIES_MISC_FORM_START + 97)
#  SPECIES_ZYGARDE_50_COMPLETE (SPECIES_MISC_FORM_START + 98)

#  SPECIES_HOOPA_UNBOUND (SPECIES_MISC_FORM_START + 99)

#  SPECIES_ORICORIO_POM_POM (SPECIES_MISC_FORM_START + 100)
#  SPECIES_ORICORIO_PAU (SPECIES_MISC_FORM_START + 101)
#  SPECIES_ORICORIO_SENSU (SPECIES_MISC_FORM_START + 102)

#  SPECIES_ROCKRUFF_OWN_TEMPO (SPECIES_MISC_FORM_START + 103)
#  SPECIES_LYCANROC_MIDNIGHT (SPECIES_MISC_FORM_START + 104)
#  SPECIES_LYCANROC_DUSK (SPECIES_MISC_FORM_START + 105)

#  SPECIES_WISHIWASHI_SCHOOL (SPECIES_MISC_FORM_START + 106)

#  SPECIES_MINIOR_METEOR_ORANGE (SPECIES_MISC_FORM_START + 107)
#  SPECIES_MINIOR_METEOR_YELLOW (SPECIES_MISC_FORM_START + 108)
#  SPECIES_MINIOR_METEOR_GREEN (SPECIES_MISC_FORM_START + 109)
#  SPECIES_MINIOR_METEOR_BLUE (SPECIES_MISC_FORM_START + 110)
#  SPECIES_MINIOR_METEOR_INDIGO (SPECIES_MISC_FORM_START + 111)
#  SPECIES_MINIOR_METEOR_VIOLET (SPECIES_MISC_FORM_START + 112)
#  SPECIES_MINIOR_CORE_RED (SPECIES_MISC_FORM_START + 113)
#  SPECIES_MINIOR_CORE_ORANGE (SPECIES_MISC_FORM_START + 114)
#  SPECIES_MINIOR_CORE_YELLOW (SPECIES_MISC_FORM_START + 115)
#  SPECIES_MINIOR_CORE_GREEN (SPECIES_MISC_FORM_START + 116)
#  SPECIES_MINIOR_CORE_BLUE (SPECIES_MISC_FORM_START + 117)
#  SPECIES_MINIOR_CORE_INDIGO (SPECIES_MISC_FORM_START + 118)
#  SPECIES_MINIOR_CORE_VIOLET (SPECIES_MISC_FORM_START + 119)

#  SPECIES_MIMIKYU_BUSTED (SPECIES_MISC_FORM_START + 120)

#  SPECIES_NECROZMA_DUSK_MANE (SPECIES_MISC_FORM_START + 121)
#  SPECIES_NECROZMA_DAWN_WINGS (SPECIES_MISC_FORM_START + 122)
#  SPECIES_NECROZMA_ULTRA_DUSK_MANE (SPECIES_MISC_FORM_START + 123)
#  SPECIES_NECROZMA_ULTRA_DAWN_WINGS (SPECIES_MISC_FORM_START + 124)

#  SPECIES_MAGEARNA_ORIGINAL (SPECIES_MISC_FORM_START + 125)

#  SPECIES_PIKACHU_PARTNER (SPECIES_MISC_FORM_START + 126)
#  SPECIES_EEVEE_PARTNER (SPECIES_MISC_FORM_START + 127)

#  SPECIES_CRAMORANT_GULPING (SPECIES_MISC_FORM_START + 128)
#  SPECIES_CRAMORANT_GORGING (SPECIES_MISC_FORM_START + 129)

#  SPECIES_TOXTRICITY_LOW_KEY (SPECIES_MISC_FORM_START + 130)

#  SPECIES_SINISTEA_ANTIQUE (SPECIES_MISC_FORM_START + 131)
#  SPECIES_POLTEAGEIST_ANTIQUE (SPECIES_MISC_FORM_START + 132)

#  SPECIES_ALCREMIE_BERRY_SWEET (SPECIES_MISC_FORM_START + 133)
#  SPECIES_ALCREMIE_LOVE_SWEET (SPECIES_MISC_FORM_START + 134)
#  SPECIES_ALCREMIE_STAR_SWEET (SPECIES_MISC_FORM_START + 135)
#  SPECIES_ALCREMIE_CLOVER_SWEET (SPECIES_MISC_FORM_START + 136)
#  SPECIES_ALCREMIE_FLOWER_SWEET (SPECIES_MISC_FORM_START + 137)
#  SPECIES_ALCREMIE_RIBBON_SWEET (SPECIES_MISC_FORM_START + 138)
#  SPECIES_ALCREMIE_FILLER_1 (SPECIES_MISC_FORM_START + 139)
#  SPECIES_ALCREMIE_FILLER_2 (SPECIES_MISC_FORM_START + 140)

#  SPECIES_EISCUE_NOICE_FACE (SPECIES_MISC_FORM_START + 141)
#  SPECIES_MORPEKO_HANGRY (SPECIES_MISC_FORM_START + 142)

#  SPECIES_ZACIAN_CROWNED (SPECIES_MISC_FORM_START + 143)
#  SPECIES_ZAMAZENTA_CROWNED (SPECIES_MISC_FORM_START + 144)

#  SPECIES_ETERNATUS_ETERNAMAX (SPECIES_MISC_FORM_START + 145)
#  SPECIES_URSHIFU_RAPID_STRIKE (SPECIES_MISC_FORM_START + 146)
#  SPECIES_ZARUDE_DADA (SPECIES_MISC_FORM_START + 147)

#  SPECIES_CALYREX_ICE_RIDER (SPECIES_MISC_FORM_START + 148)
#  SPECIES_CALYREX_SHADOW_RIDER (SPECIES_MISC_FORM_START + 149)

#  SPECIES_ENAMORUS_THERIAN (SPECIES_MISC_FORM_START + 150)

#  SPECIES_UNFEZANT_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START)
#  SPECIES_FRILLISH_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START + 1)
#  SPECIES_JELLICENT_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START + 2)
#  SPECIES_PYROAR_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START + 3)
#  SPECIES_MEOWSTIC_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START + 4)
#  SPECIES_INDEEDEE_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START + 5)
#  SPECIES_BASCULEGION_FEMALE (SPECIES_SIGNIFICANT_GENDER_DIFFERENCE_START + 6)